services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api_tesis_app
    volumes:
      - /c/Users/oquattrochi/Projects/octa/ApiTesis:/var/www/html
    ports:
      - "8123:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: api_tesis_db
    ports:
      - "3489:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_tesis
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  frontend:
    build:
      context: ../ondaFront
    container_name: frontend
    ports:
      - "9999:5173"
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
